### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by milodraco** [jangler/modplay#2]
Is possible to build it for Windows? I'm really needing a command-line mod-wav converter for my project.

**Comment by jangler** [comment]
DUMB and PortAudio work on Windows, so there shouldn't be any issues.

**Comment by milodraco** [comment]
Nice! I'm pretty much a beginner, I have no idea how to build it for Windows. I'll just to install DUMB and PortAudio and then build your software?

**Comment by milodraco** [comment]
I'm just looking for a way to convert mod->wav in cmd to improve this project:
https://github.com/milodraco/SNES-like_audio
