### ISSUE TITLE
Build fails with `error: too few arguments to function ‘dumb_load_mod_quick’` and `error: ‘duh_render’ is deprecated [-Werror=deprecated-declarations]` (GCC 14).

### ISSUE THREAD

**Issue by dreirund** [jangler/modplay#3]
Ahoj,

building this, using [this recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=modplay), with GCC 14.2.1, on [Artix GNU/Linux](http://artixlinux.org/) (rolling release), fails with two kinds of error:

* `modplay.c:145:23: error: too few arguments to function ‘dumb_load_mod_quick’`, 
* `modplay.c:178:9: error: ‘duh_render’ is deprecated [-Werror=deprecated-declarations]`.

Details:

```
cc modplay.c -Wall -Wextra -Werror -pedantic -ldumb -lportaudio -o modplay
modplay.c: In function ‘dumb_load’:
modplay.c:145:23: error: too few arguments to function ‘dumb_load_mod_quick’
  145 |                 duh = dumb_load_mod_quick(filename);
      |                       ^~~~~~~~~~~~~~~~~~~
In file included from modplay.c:9:
/usr/include/dumb.h:406:6: note: declared here
  406 | DUH *dumb_load_mod_quick(const char *filename, int restrict_);
      |      ^~~~~~~~~~~~~~~~~~~
modplay.c: In function ‘callback’:
modplay.c:178:9: error: ‘duh_render’ is deprecated [-Werror=deprecated-declarations]
  178 |         long n = duh_render(cd->sr, 16, 0, volume, cd->delta, frames, output);
      |         ^~~~
/usr/include/dumb.h:309:6: note: declared here
  309 | long duh_render(DUH_SIGRENDERER *sigrenderer, int bits, int unsign,
      |      ^~~~~~~~~~
modplay.c: In function ‘render_chunk’:
modplay.c:280:9: error: ‘duh_render’ is deprecated [-Werror=deprecated-declarations]
  280 |         long n = duh_render(cd->sr, 16, 0, volume, cd->delta, frames, buf);
      |         ^~~~
/usr/include/dumb.h:309:6: note: declared here
  309 | long duh_render(DUH_SIGRENDERER *sigrenderer, int bits, int unsign,
      |      ^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:10: all] Error 1
```

Regards!

**Comment by jangler** [comment]
The issue of modplay not being compatible with DUMB 2.0 was known already, but I see that the README was incorrectly still suggesting the AUR package as an installation method -- so that's fixed now. A proper fix would be to either update modplay for the DUMB 2.0 API or create a DUMB 1.0 package on the AUR.

**Comment by dreirund** [comment]
> *A proper fix would be to either update modplay for the DUMB 2.0 API or create a DUMB 1.0 package on the AUR.*

You seem to be the [maintainer](https://aur.archlinux.org/account/jangler) of the [AUR package](https://aur.archlinux.org/packages/modplay), too, assuming the same user name means the same person here.

So, would it then be your task to either update the AUR package (create a `dumb1` AUR package and depend on that), or orphan the AUR package, if this project here does not get updated to DUMB 2.0?

Regards!

**Comment by jangler** [comment]
Yeah, orphaning is probably the right move here. DUMB itself is unmaintained and points users to libopenmpt instead. Hopefully an Arch user can make an `openmpt123` package someday.
